package gov.geoplatform.knowstac;

@com.runwaysdk.business.ClassSignature(hash = 153872665)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to TotalEdge.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class TotalEdgeQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 153872665;

  protected TotalEdgeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends gov.geoplatform.knowstac.TotalEdgeDTO> getResultSet()
{
  return (java.util.List<? extends gov.geoplatform.knowstac.TotalEdgeDTO>)super.getResultSet();
}
}
